version: "3"
services:
 nginx:
  build:
    context: ./
    dockerfile: Dockerfile
  image: nginx
  #command: RUN rm -f /usr/share/nginx/html/*
  ports:
   - 8081:80
  volumes:
   - ./build:/usr/share/nginx/html
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.nginx.rule=Host(`app.memorystay.pl`)"
    - traefik.http.middlewares.nginx_https.redirectscheme.scheme=https
    - traefik.http.routers.nginx.entrypoints=web
    - traefik.http.routers.nginx.middlewares=nginx_https@docker
    - traefik.http.routers.nginx_https.tls=true
    - traefik.http.routers.nginx_https.entrypoints=websecure
    
