version: '3'  
services:

  nginx:
    image: nginx
    build:
      dockerfile: dockerfile
    ports:
    - 8081:80
    volumes:
      - ./build:/usr/share/nginx/html
    labels:
      - "traefik.http.routers.nginx.rule=Host(`localhost`)"
      

