version: "3"
services:
 nginx:
  build:
    context: ./
    dockerfile: Dockerfile
  image: nginx
  #command: RUN rm -f /usr/share/nginx/html/*
  ports:
   - 8081:80
  volumes:
   - ./build:/usr/share/nginx/html
  labels:
    - "traefik.http.routers.nginx.rule=Host(`app.memorystay.pl`)"

    
